apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        # This is the import path for the Go binary to build and run.
        image: github.com/afrittoli/examples/ms/go/helloworld
        ports:
        - containerPort: 8080
